// Generated by CoffeeScript 1.6.3
var isWinner, others, player;

isWinner = function(player, others) {
  var highest, _i, _len;
  highest = 0;
  for (_i = 0, _len = others.length; _i < _len; _i++) {
    player = others[_i];
    if (player.score > highest) {
      highest = player.score;
    }
  }
  return player.score > highest;
};

player = {
  name: "Abe",
  score: 10
};

others = [
  {
    name: "Bob",
    score: 2
  }, {
    name: "Carter",
    score: 3
  }
];

console.log("isWinner? " + (isWinner(player, others)));
